apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --verbose
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: conductor-ui
  name: conductor-ui
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    io.kompose.service: conductor-ui
status:
  loadBalancer: {}
