apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --verbose
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: conductor-ui
  name: conductor-ui
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: conductor-ui
    spec:
      containers:
      - env:
        - name: WF_SERVER
          value: http://conductor-server:8080/api/
        image: conductor:ui
        name: conductor-ui
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
