apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --verbose
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: dynomite
  name: dynomite
spec:
  ports:
  - name: "8102"
    port: 8102
    targetPort: 8102
  selector:
    io.kompose.service: dynomite
status:
  loadBalancer: {}
