apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --verbose
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: dynomite
  name: dynomite
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dynomite
    spec:
      containers:
      - image: v1r3n/dynomite
        livenessProbe:
          exec:
            command:
            - timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/8102'
          failureThreshold: 12
          periodSeconds: 5
          timeoutSeconds: 5
        name: dynomite
        ports:
        - containerPort: 8102
        resources: {}
      restartPolicy: Always
status: {}
